name: AVATEAM-Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build_linux:
    defaults:
      run:
        working-directory: ~/go/src/github.com/hashicorp/packer-plugin-proxmox
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/cimg/go:1.21
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: "./.github/actions/build-and-persist-plugin-binary"
      with:
        GOOS: linux
        GOARCH: amd64
